# Generated by Django 6.0.2 on 2026-02-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodule',
            name='content_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='duration',
            field=models.CharField(default='15 min', max_length=20),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='icon',
            field=models.CharField(default='AcademicCapIcon', max_length=50),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='type',
            field=models.CharField(choices=[('Quiz', 'Quiz'), ('Simulation', 'Simulation'), ('Assessment', 'Assessment')], default='Quiz', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='learningmodule',
            name='points',
            field=models.IntegerField(default=100),
        ),
    ]
