# Generated by Django 6.0.2 on 2026-03-11 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_alerts_limit_userprofile_alerts_used_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MitigatedThreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_id', models.CharField(max_length=100)),
                ('threat_title', models.CharField(max_length=255)),
                ('threat_type', models.CharField(blank=True, max_length=100)),
                ('threat_severity', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitigated_threats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'threat_id')},
            },
        ),
    ]
