# Generated by Django 6.0.2 on 2026-03-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LearningModuleHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('image', models.URLField()),
                ('alt', models.CharField(max_length=255)),
                ('completions', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LiveStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('alt', models.CharField(max_length=255)),
                ('quote', models.TextField()),
                ('rating', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('detected_date', models.CharField(max_length=100)),
                ('affected_users', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('alt', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('mitigated', 'Mitigated'), ('archived', 'Archived')], max_length=20)),
                ('community_reports', models.IntegerField(default=0)),
                ('detailed_analysis', models.TextField()),
                ('prevention_tips', models.JSONField(default=list)),
                ('real_world_examples', models.JSONField(default=list)),
                ('related_threats', models.JSONField(default=list)),
                ('community_insights', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatReportSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('date', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('affected_users', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrustSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('certification', 'Certification'), ('award', 'Award'), ('partnership', 'Partnership')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logo', models.URLField()),
                ('alt', models.CharField(max_length=255)),
            ],
        ),
    ]
