# Generated by Django 6.0.2 on 2026-03-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('free_value', models.CharField(max_length=255)),
                ('pro_value', models.CharField(max_length=255)),
                ('enterprise_value', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('monthly_price', models.IntegerField()),
                ('annual_price', models.IntegerField()),
                ('badge', models.CharField(blank=True, max_length=100, null=True)),
                ('badge_color', models.CharField(blank=True, max_length=100, null=True)),
                ('cta', models.CharField(max_length=100)),
                ('cta_style', models.CharField(max_length=255)),
                ('highlight', models.BooleanField(default=False)),
                ('icon', models.CharField(max_length=100)),
                ('icon_bg', models.CharField(max_length=100)),
                ('icon_color', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
